version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - VT_API_KEY=${VT_API_KEY}
    volumes:
      - ./data:/app/data  # Persistent volume für Rate Limit Daten
    restart: unless-stopped