version: '3.8'
services:
  linkscanner-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - rate_limit_data:/app/data
    restart: unless-stopped
    healthcheck:
      # wget verwenden statt curl (universell verfügbar)
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  rate_limit_data: